import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';

import { afterEach, describe, expect, it } from '@jest/globals';

import { BloomFilter } from '../../packages/core/dist/bloom.js';
import { assertCorpusShippable, DEFAULT_MIN_NAME_COUNT } from '../lib/shippable-corpus.mjs';

const tempDirs = [];

afterEach(() => {
  while (tempDirs.length > 0) {
    rmSync(tempDirs.pop(), { recursive: true, force: true });
  }
});

function tempCorpusDir() {
  const dir = mkdtempSync(path.join(tmpdir(), 'depguard-shippable-'));
  tempDirs.push(dir);
  return dir;
}

// A large-enough name count clears DEFAULT_MIN_NAME_COUNT (1,000,000) so
// tests that only want to exercise a different rule can use this without
// also tripping the walked-name floor. Individual tests still pass a small
// minWalkedNameCount override so they don't need a filter actually sized
// in the millions.
const PLAUSIBLE_NAME_COUNT = 1_500_000;

// Matches validMeta()'s default fpRate below, so a test that overrides
// neither gets a names.bloom on disk whose size agrees with what meta.json
// claims -- required for assertBloomSizeMatchesMeta to accept it.
const DEFAULT_TEST_FP_RATE = 0.0001;

// nameCount and fpRate are sizing parameters for the REAL bloom filter
// written to disk, independent of `names` (what actually gets inserted).
// assertBloomSizeMatchesMeta compares names.bloom's on-disk byte size
// against what meta.nameCount/meta.fpRate imply, derived by calling
// BloomFilter.create the same way the gate does -- so any test whose
// meta.json claims a nameCount/fpRate has to build its filter with those
// same values here, or the geometry check (correctly) refuses it. Sizing
// depends only on the count and fpRate BloomFilter.create is given, never
// on how many names are actually inserted, so `names` can stay a short,
// realistic list even when nameCount is in the millions -- for every test
// below that never reaches the fill-ratio check (assertBloomFillRatioPlausible
// in shippable-corpus.mjs), because it throws for some other, earlier
// reason first. The handful of tests that exercise the full accept path
// need the fill-ratio check to pass too, so they pass an explicit `names`
// generated by generatedNames() below, sized to actually match their
// claimed nameCount.
function writeCorpusFiles(
  dir,
  { names = ['react'], top = ['react'], aliases = {}, nameCount = PLAUSIBLE_NAME_COUNT, fpRate = DEFAULT_TEST_FP_RATE } = {}
) {
  const filter = BloomFilter.create(names, nameCount, fpRate);
  writeFileSync(path.join(dir, 'names.bloom'), filter.serialize());
  writeFileSync(path.join(dir, 'top.json'), JSON.stringify(top));
  writeFileSync(path.join(dir, 'aliases.json'), JSON.stringify(aliases));
}

// Generates `count` distinct package-shaped names, always including
// 'react' first so assertLoadsAndResolvesKnownName still finds it. Used
// only where a test needs a bloom filter actually populated near its
// claimed nameCount, for the fill-ratio check -- kept to counts in the
// low thousands in this file so those tests stay fast; the check's own
// math does not care whether the real count is 2,000 or 2,000,000.
function generatedNames(count) {
  const names = ['react'];
  for (let i = names.length; i < count; i++) {
    names.push(`walked-pkg-${i}`);
  }
  return names;
}

function writeMeta(dir, meta) {
  writeFileSync(path.join(dir, 'meta.json'), JSON.stringify(meta));
}

// The full set of fields a real, ready-to-publish meta.json carries, so
// each test only has to override the one field it's exercising.
function validMeta(overrides = {}) {
  return {
    formatVersion: 1,
    builtAt: '2026-08-18T00:00:00.000Z',
    nameCount: PLAUSIBLE_NAME_COUNT,
    fpRate: DEFAULT_TEST_FP_RATE,
    walkComplete: true,
    ...overrides,
  };
}

describe('assertCorpusShippable', () => {
  it('accepts a corpus with all four files, present-and-correct formatVersion and walkComplete, and a nameCount clearing a low test floor', () => {
    const dir = tempCorpusDir();
    // This test's floor override (1) means nameCount does not need to be
    // realistic, so a small, fully-populated filter (rather than
    // PLAUSIBLE_NAME_COUNT's 1.5 million) keeps this test fast while still
    // satisfying the fill-ratio check, which needs the claimed count to
    // actually be inserted.
    const NAME_COUNT = 2000;
    writeCorpusFiles(dir, { names: generatedNames(NAME_COUNT), nameCount: NAME_COUNT });
    writeMeta(dir, validMeta({ nameCount: NAME_COUNT }));

    expect(() => assertCorpusShippable(dir, 1)).not.toThrow();
  });

  it('refuses a directory missing one of the four required files', () => {
    const dir = tempCorpusDir();
    writeCorpusFiles(dir);
    writeMeta(dir, validMeta());
    rmSync(path.join(dir, 'aliases.json'));

    expect(() => assertCorpusShippable(dir, 1)).toThrow(/aliases\.json/);
  });

  it('refuses a directory missing meta.json itself', () => {
    const dir = tempCorpusDir();
    writeCorpusFiles(dir);
    writeMeta(dir, validMeta());
    rmSync(path.join(dir, 'meta.json'));

    expect(() => assertCorpusShippable(dir, 1)).toThrow(/meta\.json/);
  });

  // readMeta's two failure branches, exercised directly: a meta.json that
  // exists (so assertRequiredFilesPresent does not catch it) but cannot be
  // read as a file, and one that reads fine but is not valid JSON.
  it('refuses a corpus whose meta.json cannot be read as a file', () => {
    const dir = tempCorpusDir();
    writeCorpusFiles(dir);
    // A directory in place of meta.json reproduces "exists but cannot be
    // read as a file" (readFileSync throws EISDIR) without relying on
    // chmod, which a test runner with elevated privileges can bypass.
    mkdirSync(path.join(dir, 'meta.json'));

    expect(() => assertCorpusShippable(dir, 1)).toThrow(/could not read/);
  });

  it('refuses a corpus whose meta.json is not valid JSON', () => {
    const dir = tempCorpusDir();
    writeCorpusFiles(dir);
    writeFileSync(path.join(dir, 'meta.json'), 'not json');

    expect(() => assertCorpusShippable(dir, 1)).toThrow(/not valid JSON/);
  });

  // The whole point of this gate: the reader tolerates an absent
  // formatVersion (a pre-versioning local artifact excuse), but nothing
  // about to be published gets that excuse.
  it('refuses a corpus whose meta.json has no formatVersion, even though loadCorpus itself would accept it', () => {
    const dir = tempCorpusDir();
    writeCorpusFiles(dir);
    writeMeta(dir, validMeta({ formatVersion: undefined }));

    // Matches the PRESENCE-check message specifically (assertFormatVersion-
    // PresentAndSupported's "has no formatVersion" branch), not the
    // present-but-wrong-value message ("formatVersion is X, which this
    // build does not understand") that a deleted presence check would fall
    // through to. A bare /formatVersion/ regex would pass either way and
    // not actually prove the presence check ran.
    expect(() => assertCorpusShippable(dir, 1)).toThrow(/has no formatVersion/);
  });

  it('refuses a corpus whose formatVersion is not one this build understands', () => {
    const dir = tempCorpusDir();
    writeCorpusFiles(dir);
    writeMeta(dir, validMeta({ formatVersion: 2 }));

    expect(() => assertCorpusShippable(dir, 1)).toThrow(/formatVersion/);
  });

  // The other half of the whole point: the reader tolerates an absent
  // walkComplete for the same pre-versioning-artifact reason, and this gate
  // does not extend that tolerance to a corpus about to ship.
  it('refuses a corpus whose meta.json has no walkComplete, even though loadCorpus itself would accept it', () => {
    const dir = tempCorpusDir();
    writeCorpusFiles(dir);
    writeMeta(dir, validMeta({ walkComplete: undefined }));

    // Matches the PRESENCE-check message specifically (assertWalkComplete-
    // PresentAndTrue's "has no walkComplete" branch), not the
    // present-but-wrong-value message ("walkComplete is X, not true") that
    // a deleted presence check would fall through to. A bare /walkComplete/
    // regex would pass either way and not actually prove the presence
    // check ran.
    expect(() => assertCorpusShippable(dir, 1)).toThrow(/has no walkComplete/);
  });

  it('refuses a corpus whose walkComplete is false', () => {
    const dir = tempCorpusDir();
    writeCorpusFiles(dir);
    writeMeta(dir, validMeta({ walkComplete: false }));

    expect(() => assertCorpusShippable(dir, 1)).toThrow(/walkComplete/);
  });

  it('refuses a corpus whose walkComplete is truthy but not the literal boolean true', () => {
    const dir = tempCorpusDir();
    writeCorpusFiles(dir);
    writeMeta(dir, validMeta({ walkComplete: 'true' }));

    expect(() => assertCorpusShippable(dir, 1)).toThrow(/walkComplete/);
  });

  it('refuses a corpus whose nameCount is below the minimum floor', () => {
    const dir = tempCorpusDir();
    writeCorpusFiles(dir);
    writeMeta(dir, validMeta({ nameCount: 999 }));

    expect(() => assertCorpusShippable(dir, 1000)).toThrow(/nameCount/);
  });

  it('accepts a corpus whose walked name count meets the minimum floor exactly', () => {
    const dir = tempCorpusDir();
    // top: [] means no curated extras, so the entire claimed nameCount has
    // to come from the walk -- this test is about the walked-name floor
    // exactly, not about a top list padding it out to reach it. names is a
    // real 1000-name walk, not the ['react']-only default, so the claimed
    // count is actually inserted, for the fill-ratio check.
    writeCorpusFiles(dir, { names: generatedNames(1000), top: [], nameCount: 1000, fpRate: DEFAULT_TEST_FP_RATE });
    writeMeta(dir, validMeta({ nameCount: 1000 }));

    expect(() => assertCorpusShippable(dir, 1000)).not.toThrow();
  });

  // DEFAULT_MIN_NAME_COUNT is what the command-line entry point (and
  // therefore the release workflow) actually uses -- proves it is set high
  // enough that corpus:slice's own default (20,000 names, per
  // package.json's "corpus:slice" script) could never pass it by accident.
  it('the default floor refuses a corpus:slice-sized nameCount (20,000)', () => {
    const dir = tempCorpusDir();
    writeCorpusFiles(dir);
    writeMeta(dir, validMeta({ nameCount: 20_000 }));

    expect(() => assertCorpusShippable(dir)).toThrow(/nameCount/);
    expect(DEFAULT_MIN_NAME_COUNT).toBeGreaterThan(20_000);
  });

  // The whole reason this floor is on the WALKED count rather than the
  // bare nameCount field: a bare "nameCount >= floor" check could in
  // principle be satisfied by an inflated top.json alone, with the walk
  // itself having contributed almost nothing.
  it('refuses a corpus whose nameCount clears the floor but is almost entirely injected extras, not walked names', () => {
    const dir = tempCorpusDir();
    const injectedExtras = Array.from({ length: 995 }, (_, i) => `extra-pkg-${i}`);
    writeCorpusFiles(dir, { top: injectedExtras, nameCount: 1000, fpRate: DEFAULT_TEST_FP_RATE });
    writeMeta(dir, validMeta({ nameCount: 1000 }));

    // The bare nameCount (1000) clears a floor of 100 easily. Only 5 of
    // those 1000 names were actually walked (1000 claimed minus 995
    // injected extras from top.json), which does not.
    expect(() => assertCorpusShippable(dir, 100)).toThrow(/walk itself contributed/);
  });

  describe('the bloom-size-matches-meta geometry cross-check', () => {
    it('accepts a corpus whose names.bloom size on disk matches what meta.nameCount and meta.fpRate imply', () => {
      const dir = tempCorpusDir();
      // A real 50-name walk, not the ['react']-only default, so this also
      // clears the fill-ratio check below.
      writeCorpusFiles(dir, { names: generatedNames(50), nameCount: 50, fpRate: 0.01 });
      writeMeta(dir, validMeta({ nameCount: 50, fpRate: 0.01 }));

      expect(() => assertCorpusShippable(dir, 1)).not.toThrow();
    });

    // The essential case (b) exists for: a hand-edited or stale meta.json
    // claiming a nameCount the physical filter never grew to match. Every
    // field in meta.json reads as a plausible type; only the size
    // cross-check against the real artifact on disk catches it.
    it('refuses a corpus whose meta.nameCount is inflated far beyond what names.bloom on disk could hold', () => {
      const dir = tempCorpusDir();
      // The bloom file on disk is genuinely small (sized for 50 names).
      writeCorpusFiles(dir, { nameCount: 50, fpRate: DEFAULT_TEST_FP_RATE });
      // meta.json claims a huge nameCount with the same fpRate -- the
      // walked-name floor (a) would happily accept this on the numbers
      // alone; only the geometry check catches that the file on disk
      // never actually grew.
      writeMeta(dir, validMeta({ nameCount: 2_000_000, fpRate: DEFAULT_TEST_FP_RATE }));

      expect(() => assertCorpusShippable(dir, 1)).toThrow(/names\.bloom/);
    });

    it('refuses a corpus whose meta.fpRate is missing', () => {
      const dir = tempCorpusDir();
      writeCorpusFiles(dir, { nameCount: 50, fpRate: DEFAULT_TEST_FP_RATE });
      writeMeta(dir, validMeta({ nameCount: 50, fpRate: undefined }));

      expect(() => assertCorpusShippable(dir, 1)).toThrow(/fpRate/);
    });

    it('refuses a corpus whose meta.fpRate is not a usable rate (zero)', () => {
      const dir = tempCorpusDir();
      writeCorpusFiles(dir, { nameCount: 50, fpRate: DEFAULT_TEST_FP_RATE });
      writeMeta(dir, validMeta({ nameCount: 50, fpRate: 0 }));

      expect(() => assertCorpusShippable(dir, 1)).toThrow(/fpRate/);
    });
  });

  it('refuses a corpus whose files are well-formed but does not load through the real reader (malformed JSON)', () => {
    const dir = tempCorpusDir();
    writeCorpusFiles(dir);
    writeMeta(dir, validMeta());
    // Overwrite top.json with something loadCorpus rejects (not an array).
    writeFileSync(path.join(dir, 'top.json'), JSON.stringify({ react: 1 }));

    expect(() => assertCorpusShippable(dir, 1)).toThrow(/real reader/);
  });

  it('refuses a corpus that loads fine but does not resolve a known-popular name as present', () => {
    const dir = tempCorpusDir();
    // Filter built over names that do not include "react" at all.
    writeCorpusFiles(dir, { names: ['some-other-package'], top: ['some-other-package'] });
    writeMeta(dir, validMeta());

    expect(() => assertCorpusShippable(dir, 1)).toThrow(/react/);
  });

  // The essential case this check exists for: assertBloomSizeMatchesMeta
  // (the geometry cross-check above) proves only that names.bloom's SIZE
  // matches what meta.nameCount/meta.fpRate imply -- BloomFilter.create
  // sizes its bit array from count and fpRate alone, never from what is
  // actually inserted, so an optimally-sized filter with near-zero real
  // content passes that check exactly as cleanly as a fully-populated one.
  // 'react' resolving (assertLoadsAndResolvesKnownName) does not catch it
  // either, because collectExtras injects every top-list name regardless
  // of what the walk found. This is the physical check that looks at what
  // the bit array actually holds.
  describe('the bit-fill-ratio check', () => {
    it('accepts a corpus whose bloom filter is actually populated near its claimed nameCount', () => {
      const dir = tempCorpusDir();
      const NAME_COUNT = 3000;
      writeCorpusFiles(dir, {
        names: generatedNames(NAME_COUNT),
        top: [],
        nameCount: NAME_COUNT,
        fpRate: DEFAULT_TEST_FP_RATE,
      });
      writeMeta(dir, validMeta({ nameCount: NAME_COUNT }));

      expect(() => assertCorpusShippable(dir, 1)).not.toThrow();
    });

    // The empty-but-well-formed corpus scenario the whole check exists
    // for: a filter sized for a large claimed nameCount (1.5 million, same
    // as a real shipped corpus's order of magnitude) but with only a
    // single name actually inserted -- exactly what a truncated or
    // misread name store produces while the walk still self-reports
    // complete. Every other check in this gate accepts this corpus; only
    // the fill-ratio check catches it.
    it('refuses a filter with a large claimed nameCount but only a handful of names actually inserted', () => {
      const dir = tempCorpusDir();
      writeCorpusFiles(dir, {
        names: ['react'],
        top: ['react'],
        nameCount: 1_500_000,
        fpRate: DEFAULT_TEST_FP_RATE,
      });
      writeMeta(dir, validMeta({ nameCount: 1_500_000 }));

      expect(() => assertCorpusShippable(dir, 1)).toThrow(/bit-fill ratio/);
    });
  });

  // fillRatioOf's own fail-closed guard -- the instanceof Uint8Array /
  // typeof / Number.isFinite check on the bits and bitCount read back off
  // a deserialized BloomFilter, before any arithmetic runs on them -- has
  // no test reaching it through on-disk corruption, and this describe
  // block establishes why: it cannot be reached that way at all, for two
  // independent reasons that both hold before fillRatioOf ever runs.
  //
  //   1. assertBloomSizeMatchesMeta (checked earlier in
  //      assertCorpusShippable) only accepts a names.bloom whose on-disk
  //      byte length exactly matches what BloomFilter.create(meta.nameCount,
  //      meta.fpRate) implies. BloomFilter.create's minimum bitCount is 8
  //      (bloom.ts: `Math.max(8, ...)`), which is at least one byte of bit
  //      array, so a header-only file with zero bits bytes can never match
  //      that expected size regardless of what meta.json claims -- it is
  //      rejected before fillRatioOf runs at all.
  //   2. A names.bloom whose SIZE does match still has to survive
  //      BloomFilter.deserialize's own checks (magic, version, bitCount
  //      and hashCount both >= 1, and a length check against the header's
  //      OWN claimed bitCount) before it returns an object. Every field on
  //      what it returns is a well-typed Uint8Array/number, because
  //      deserialize constructs bits and bitCount itself from validated
  //      input -- there is no on-disk byte pattern that survives both
  //      assertBloomSizeMatchesMeta and BloomFilter.deserialize while
  //      still producing a malformed bits/bitCount pair for the guard to
  //      catch.
  //
  // What IS reachable is BloomFilter.deserialize rejecting a corrupted
  // file outright -- exercised below, reached through
  // assertLoadsAndResolvesKnownName's corpus.hasName() call (loadCorpus()
  // itself never touches names.bloom; it is read lazily -- see
  // corpus.ts's loadBloom), which runs before assertBloomFillRatioPlausible
  // and is not wrapped in that function's own try/catch, so the
  // DepGuardError from bloom.ts propagates as-is. The guard in fillRatioOf
  // stays defensive code for a future refactor of BloomFilter's compiled
  // shape (a real JS #private field, a renamed property -- see the
  // comment above fillRatioOf in shippable-corpus.mjs), not for on-disk
  // corruption, which is caught earlier by the two checks above.
  describe('names.bloom corruption that IS reachable (the fail-closed guard above is not, see comment)', () => {
    it('refuses a corpus whose names.bloom has the right byte size but a corrupted magic header', () => {
      const dir = tempCorpusDir();
      // A real, correctly-sized filter first, so assertBloomSizeMatchesMeta
      // (which runs before assertLoadsAndResolvesKnownName) sees a byte
      // length that matches what meta.json claims.
      writeCorpusFiles(dir, { names: generatedNames(50), nameCount: 50, fpRate: 0.01 });
      writeMeta(dir, validMeta({ nameCount: 50, fpRate: 0.01 }));

      // Corrupt only the first (magic) byte on disk, in place -- byte
      // length is untouched, so the geometry cross-check still passes and
      // this reaches BloomFilter.deserialize itself.
      const bloomPath = path.join(dir, 'names.bloom');
      const corrupted = Buffer.from(readFileSync(bloomPath));
      corrupted[0] = 0x00;
      writeFileSync(bloomPath, corrupted);

      expect(() => assertCorpusShippable(dir, 1)).toThrow(/bloom filter magic mismatch/);
    });
  });
});
